import enum


class TransactionType(str, enum.Enum):
    UPI = "UPI"
    ATM = "ATM"
    DEBIT_CARD = "DEBIT_CARD"
    CREDIT_CARD = "CREDIT_CARD"
    NEFT = "NEFT"
    RTGS = "RTGS"
    IMPS = "IMPS"


class TransactionStatus(str, enum.Enum):
    APPROVED = "APPROVED"
    REVIEW = "REVIEW"
    OTP_PENDING = "OTP_PENDING"
    BLOCKED = "BLOCKED"
    PENDING = "PENDING"


class Decision(str, enum.Enum):
    APPROVE = "APPROVE"
    REVIEW = "REVIEW"
    OTP_VERIFICATION = "OTP_VERIFICATION"
    BLOCK = "BLOCK"


class CustomerStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    DORMANT = "DORMANT"
    CLOSED = "CLOSED"
    SUSPENDED = "SUSPENDED"


class RiskSegment(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class AlertSeverity(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlertStatus(str, enum.Enum):
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    CLOSED = "CLOSED"


class DeviceType(str, enum.Enum):
    MOBILE = "MOBILE"
    DESKTOP = "DESKTOP"
    ATM_TERMINAL = "ATM_TERMINAL"
    POS_TERMINAL = "POS_TERMINAL"


class BlacklistEntityType(str, enum.Enum):
    MERCHANT = "MERCHANT"
    IP_ADDRESS = "IP_ADDRESS"
    DEVICE = "DEVICE"
    ACCOUNT = "ACCOUNT"
    COUNTRY = "COUNTRY"
    BENEFICIARY = "BENEFICIARY"


class InvestigationAction(str, enum.Enum):
    ASSIGN = "ASSIGN"
    NOTE = "NOTE"
    APPROVE = "APPROVE"
    BLOCK = "BLOCK"
    MARK_SAFE = "MARK_SAFE"
    CLOSE = "CLOSE"
    ESCALATE = "ESCALATE"
    FREEZE_ACCOUNT = "FREEZE_ACCOUNT"
    REQUEST_VERIFICATION = "REQUEST_VERIFICATION"


class FraudScenario(str, enum.Enum):
    LARGE_TRANSACTION = "LARGE_TRANSACTION"
    NEW_DEVICE = "NEW_DEVICE"
    FOREIGN_LOCATION = "FOREIGN_LOCATION"
    IMPOSSIBLE_TRAVEL = "IMPOSSIBLE_TRAVEL"
    RAPID_MULTIPLE_TRANSACTIONS = "RAPID_MULTIPLE_TRANSACTIONS"
    NEW_BENEFICIARY = "NEW_BENEFICIARY"
    BLACKLISTED_MERCHANT = "BLACKLISTED_MERCHANT"
    BLACKLISTED_IP = "BLACKLISTED_IP"
    DORMANT_ACCOUNT_ACTIVE = "DORMANT_ACCOUNT_ACTIVE"
    REPEATED_FAILED_LOGIN = "REPEATED_FAILED_LOGIN"
    MULTIPLE_CARDS_SAME_IP = "MULTIPLE_CARDS_SAME_IP"
    VELOCITY_FRAUD = "VELOCITY_FRAUD"
    MONEY_MULE = "MONEY_MULE"
    ACCOUNT_TAKEOVER = "ACCOUNT_TAKEOVER"
    ROUND_NUMBER_LAUNDERING = "ROUND_NUMBER_LAUNDERING"
    STRUCTURING = "STRUCTURING"
    TRANSACTION_SPLITTING = "TRANSACTION_SPLITTING"
    ATM_CASH_OUT_ATTACK = "ATM_CASH_OUT_ATTACK"
