"""Generates a plain-text investigation report for a fraud alert — the
"Generate Investigation Report" action in the analyst workspace."""

from app.models.fraud_alert import FraudAlert


def build_investigation_report(alert: FraudAlert) -> str:
    txn = alert.transaction
    customer = alert.customer
    lines = [
        "=" * 72,
        "PiBy3 FRAUD INTELLIGENCE PLATFORM",
        "CONFIDENTIAL — INVESTIGATION REPORT",
        "=" * 72,
        "",
        f"Alert Reference:      {alert.alert_ref}",
        f"Generated:            {alert.updated_at.isoformat()}",
        "Prepared By:          Enterprise Fraud Intelligence Platform",
        f"Status:               {alert.status}",
        f"Severity:             {alert.severity}",
        "",
        "-" * 72,
        "CUSTOMER",
        "-" * 72,
        f"Name:                 {customer.full_name}",
        f"Customer Code:        {customer.customer_code}",
        f"Risk Segment:         {customer.risk_segment}",
        f"City / State:         {customer.city}, {customer.state}",
        "",
        "-" * 72,
        "TRANSACTION",
        "-" * 72,
        f"Reference:            {txn.transaction_ref}",
        f"Amount:               {txn.currency} {float(txn.amount):,.2f}",
        f"Channel:              {txn.transaction_type}",
        f"Timestamp:            {txn.timestamp.isoformat()}",
        f"Location:             {txn.city}, {txn.country.name}",
        f"IP Address:           {txn.ip_address}",
        f"Device:               {txn.device.device_uid if txn.device else 'Unregistered'}",
        f"Status:               {txn.status}",
        f"Decision:             {txn.decision}",
        f"Risk Score:           {txn.risk_score:.0f} / 100",
        "",
        "-" * 72,
        "WHY THIS WAS FLAGGED",
        "-" * 72,
    ]
    for point in alert.explanation:
        lines.append(f"  - {point}")

    lines += [
        "",
        "-" * 72,
        "RULE EVALUATION",
        "-" * 72,
    ]
    for rule in txn.rule_evaluations or []:
        verdict = "TRIGGERED" if rule["triggered"] else "passed"
        lines.append(f"  [{verdict:>9}] {rule['name']} (weight {rule['weight']:.0f}) — {rule['detail']}")

    lines += [
        "",
        "-" * 72,
        "INVESTIGATION TIMELINE",
        "-" * 72,
    ]
    for inv in sorted(alert.investigations, key=lambda i: i.created_at):
        lines.append(f"  {inv.created_at.isoformat()}  {inv.action:<22} {inv.investigator} — {inv.notes}")

    lines += [
        "",
        "=" * 72,
        f"Report generated by the PiBy3 Fraud Intelligence Platform for {customer.full_name}.",
        "CONFIDENTIAL — For authorized internal use only. Do not distribute externally.",
        "PiBy3 · Enterprise AI Solutions · Transforming Enterprises for the Future",
        "=" * 72,
    ]
    return "\n".join(lines)
