RULE_DEFINITIONS = [
    {
        "code": "AMOUNT_ANOMALY",
        "name": "Amount Anomaly",
        "description": "Transaction amount significantly exceeds the customer's historical average transaction amount.",
        "category": "AMOUNT",
        "weight": 25,
        "threshold": 5,
        "config": {"multiplier": 5},
        "priority": 10,
    },
    {
        "code": "LARGE_AMOUNT",
        "name": "Large Transaction Amount",
        "description": "Transaction amount exceeds the configured high-value threshold of ₹1,00,000.",
        "category": "AMOUNT",
        "weight": 20,
        "threshold": 100000,
        "config": {"amount_threshold": 100000},
        "priority": 20,
    },
    {
        "code": "NEW_DEVICE",
        "name": "New / Unrecognized Device",
        "description": "Transaction initiated from a device not previously associated with this customer.",
        "category": "DEVICE",
        "weight": 35,
        "threshold": None,
        "config": {},
        "priority": 30,
    },
    {
        "code": "FOREIGN_COUNTRY",
        "name": "Foreign Country Transaction",
        "description": "Transaction originates from a country outside the customer's home country.",
        "category": "LOCATION",
        "weight": 35,
        "threshold": None,
        "config": {},
        "priority": 15,
    },
    {
        "code": "IMPOSSIBLE_TRAVEL",
        "name": "Impossible Travel Velocity",
        "description": "Two transactions occurred at locations further apart than could be physically travelled in the elapsed time.",
        "category": "LOCATION",
        "weight": 35,
        "threshold": 900,
        "config": {"max_speed_kmh": 900},
        "priority": 5,
    },
    {
        "code": "VELOCITY_BURST",
        "name": "High Velocity - Rapid Multiple Transactions",
        "description": "5 or more transactions detected for this customer within a 30 second window.",
        "category": "VELOCITY",
        "weight": 35,
        "threshold": 5,
        "config": {"count": 5, "window_seconds": 30},
        "priority": 12,
    },
    {
        "code": "NEW_BENEFICIARY",
        "name": "New Beneficiary",
        "description": "Funds transferred to a beneficiary that has never received a transfer from this customer before.",
        "category": "BENEFICIARY",
        "weight": 35,
        "threshold": None,
        "config": {},
        "priority": 40,
    },
    {
        "code": "BLACKLISTED_MERCHANT",
        "name": "Blacklisted Merchant",
        "description": "Transaction routed to a merchant present on the fraud blacklist.",
        "category": "MERCHANT",
        "weight": 45,
        "threshold": None,
        "config": {},
        "priority": 3,
    },
    {
        "code": "BLACKLISTED_IP",
        "name": "Blacklisted IP Address",
        "description": "Originating IP address is present on the known fraud / botnet blacklist.",
        "category": "NETWORK",
        "weight": 40,
        "threshold": None,
        "config": {},
        "priority": 4,
    },
    {
        "code": "DORMANT_ACCOUNT_ACTIVE",
        "name": "Dormant Account Suddenly Active",
        "description": "Account with no activity for 90+ days has suddenly initiated a transaction.",
        "category": "BEHAVIOR",
        "weight": 35,
        "threshold": 90,
        "config": {"dormant_days": 90},
        "priority": 25,
    },
    {
        "code": "ROUND_NUMBER_LAUNDERING",
        "name": "Round Number Pattern",
        "description": "Transaction amount is a suspiciously round number, a common indicator of layering / laundering.",
        "category": "PATTERN",
        "weight": 12,
        "threshold": None,
        "config": {},
        "priority": 60,
    },
    {
        "code": "STRUCTURING",
        "name": "Structuring - Sub-threshold Transfers",
        "description": "Multiple transfers just under the reporting threshold executed in a short window.",
        "category": "PATTERN",
        "weight": 30,
        "threshold": 100000,
        "config": {"threshold": 100000, "window_minutes": 60, "count": 3},
        "priority": 18,
    },
    {
        "code": "MULTIPLE_CARDS_SAME_IP",
        "name": "Multiple Accounts on Same IP",
        "description": "Several distinct customer accounts have transacted from the same IP address in a short window.",
        "category": "NETWORK",
        "weight": 35,
        "threshold": 3,
        "config": {"window_minutes": 10, "account_count": 3},
        "priority": 22,
    },
    {
        "code": "ODD_HOUR_ACTIVITY",
        "name": "Odd Hour Transaction",
        "description": "Transaction occurred well outside the customer's typical active hours.",
        "category": "BEHAVIOR",
        "weight": 10,
        "threshold": None,
        "config": {},
        "priority": 70,
    },
    {
        "code": "REPEATED_FAILED_LOGIN",
        "name": "Repeated Failed Login Attempts",
        "description": "Multiple failed authentication attempts were recorded shortly before this transaction.",
        "category": "AUTH",
        "weight": 25,
        "threshold": 3,
        "config": {"count": 3},
        "priority": 14,
    },
    {
        "code": "TRANSACTION_SPLITTING",
        "name": "Transaction Splitting to Same Beneficiary",
        "description": "Multiple transfers sent to the same beneficiary in quick succession, consistent with splitting a larger payment to avoid scrutiny.",
        "category": "PATTERN",
        "weight": 35,
        "threshold": 3,
        "config": {"count": 3, "window_minutes": 30},
        "priority": 16,
    },
    {
        "code": "ACCOUNT_TAKEOVER_PATTERN",
        "name": "Account Takeover Indicators",
        "description": "Combination of new device, new location and a beneficiary change suggests possible account takeover.",
        "category": "BEHAVIOR",
        "weight": 35,
        "threshold": None,
        "config": {},
        "priority": 8,
    },
]
